config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :tasks do
    patch 'update_status', on: :member
    resources :comments, only: [:new, :create]
    collection do
      get 'filter_by_date', to: 'tasks#filter_by_date'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/task.rb
class Task < ApplicationRecord
    has_and_belongs_to_many :roles, :join_table => :tasks_roles
    has_and_belongs_to_many :users, :join_table => :task_users
    has_many :comments, dependent: :destroy


    before_create :set_default_status

    private
  
    def set_default_status
      self.task_status ||= true
    end
  end

app/models/task_user.rb
class TaskUser < ApplicationRecord
end

app/models/tasks_role.rb
class TasksRole < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify


  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  
  devise :database_authenticatable, :authentication_keys => [:username]
  
  validates :email, uniqueness: true
  validates :username, uniqueness: true

  after_create :assign_role

  def assign_role
    if User.all.count == 1 
      User.first.add_role :admin
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :null_session, only: [:create]
    before_action :authenticate_user!

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @task = Task.find(params[:task_id])
        @comment = @task.comments.new
      end
    
      def create
        @task = Task.find(params[:task_id])
        @comment = @task.comments.new(comment_params)
    
        if @comment.save
          respond_to do |format|
            format.html { redirect_to @task }
            format.js   # This will render create.js.erb
          end
        else
          # Handle error case
        end
      end
    
      private
    
      def comment_params
        params.require(:comment).permit(:content)
      end
    end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
      @date_method = (params[:search].present? ? params[:search][:date_method] : 'indate').to_sym
      @start = selected_date(:start_date)
      @end = selected_date(:end_date)
      if current_user.has_role?(:admin)
        @roles = Role.pluck(:name)
        @tasks_ids = TasksRole.all
        @tasks = params[:search].present? ? Task.all.joins(:users).select("tasks.*, users.username").where(@date_method => @start..@end).order(task_urgency: :desc) : Task.all.joins(:users).select("tasks.*, users.username").order(task_urgency: :desc)
        @tasks_normal = @tasks.select { |x| x.task_urgency == 1 }
        @tasks_prioridade = @tasks.select { |x| x.task_urgency == 2 }
        @tasks_urgente = @tasks.select { |x| x.task_urgency == 3 }
        
      else
        @users = current_user
        @roles = @users.roles.pluck(:id)
        @tasks_ids = params[:search].present? ? TasksRole.where(role_id: @role_task).pluck(:task_id) : TasksRole.where(role_id: @roles).pluck(:task_id)
        @tasks = Task.where(id: @tasks_ids).joins(:users).select("tasks.*, users.username")
        @tasks_normal = @tasks.select { |x| x.task_urgency == 1 }
        @tasks_prioridade = @tasks.select { |x| x.task_urgency == 2 }
        @tasks_urgente = @tasks.select { |x| x.task_urgency == 3 }

      end

    end
    def show
      @task = Task.find(params[:id])
      @comments = @task.comments
      puts @comments
      respond_to do |format|
        format.js
      end

    rescue ActionController::UnknownFormat
      render status: 404, text: "Not Found"
    end
    def new
      @task = Task.new
      if current_user.has_role?(:admin)
        @roles = Role.pluck(:name,:id)
      else
        @users = current_user
        @roles = @users.roles.pluck(:name,:id)
        
      end
  
    end
    def create
      @task = Task.new(task_params)
      @task.user_ids = current_user.id
  
      if @task.save
        redirect_to @task
      else
        render :new, status: :unprocessable_entity
      end
    end
    def update_status
      @task = Task.find(params[:id])
      if @task.task_status == false 
        @task.update(task_status: true)
      else
        @task.update(task_status: false)
      end
      respond_to do |format|
        format.js
      end
    end
    def filter_by_date
      start_date = params[:start_date].to_date
      end_date = params[:end_date].to_date
  
      @tasks = Task.where(task_expire: start_date..end_date)
  
      respond_to do |format|
        format.js
      end
    end

  
    private
      def task_params
        params.require(:task).permit(:task_name, :task_content, :task_urgency, :task_expire, role_ids: [],user_ids: [])
      end

      def selected_date(symbol)
        params[:search].present? && params[:search][symbol].present? ? params[:search][symbol].to_date : Time.now.to_date
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<li>
  <p><%= comment.content %></p>
  <!-- Add any other comment details you want to display -->
</li>

app/views/comments/_form.html.erb
<%= form_with(model: [ @task, @comment ], remote: true) do |form| %>
  <%= form.text_area :content, placeholder: "Enter your comment" %>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/comments/create.js.erb
// Clear the comment input field
document.getElementById('comment_content').value = '';

// Append the newly created comment to the comments list
var commentsList = document.getElementById('comments_list');
var newComment = document.createElement('li');
newComment.innerHTML = '<%= j render partial: "comment", locals: { comment: @comment } %>';
commentsList.appendChild(newComment);

app/views/comments/new.html.erb
<%= form_with(model: [ @task, @comment ], remote: true) do |form| %>
    <%= form.text_area :content, placeholder: "Enter your comment" %>
    <%= form.submit "Add Comment" %>
<% end %>

app/views/comments/new.js.erb
document.getElementById('comment_form_container').innerHTML = '<%= j render "form" %>';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskController</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
  <section class="vh-100" style="background-color: #eee;">
  <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <div class="container-xl">
      <div class="row d-flex justify-content-center align-items-center">
          <div class="card">
            <div class="card-header p-3">
            <%= link_to "Criar nova tarefa", new_task_path, remote: true %>
              <h5 class="mb-0"><i class="fas fa-tasks me-2"></i>Tarefas</h5>
              <%= form_for :search, method: :get do |f| -%>

                <%= f.select :date_method, options_for_select( [['Data de expiracao','task_expire'],['Data de criacao','created_at']], selected: @date_method ) -%>
                <%= f.date_field :start_date, value: @start -%>
                <%= f.date_field :end_date, value: @end -%>
                <%= f.select :role_ids, options_for_select(@roles), selected: @role_task, value: @role_name %>
                <%= f.submit 'Search' -%>
            
              <% end -%>
            </div>
            <div class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative">
              <table class="table mb-0">
                <thead>
                  <tr>
                    <th scope="col">Autor</th>
                    <th scope="col">Tarefa</th>
                    <th scope="col">Prioridade</th>
                    <th scope="col">Data Limite</th>
                    <th scope="col">Status</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
                <tbody>
                <% @tasks.each do |task| %>
                  <tr class="align-middle">
                    <th>
                      <span class="ms-2"><%= task.username %></span>
                    </th>
                    <td class="align-middle">
                      <span><%= task.task_name %></span>
                    </td>
                    <td class="align-middle">
                    <% if task.task_urgency == 1 %>
                      <h6 class="mb-0"><span class="badge bg-danger">Tarefa normal</span></h6>
                    <% elsif task.task_urgency == 2 %>
                      <h6 class="mb-0"><span class="badge bg-danger">Tarefa com prioridade</span></h6>
                    <% else %>
                      <h6 class="mb-0"><span class="badge bg-danger">Tarefa com urgencia</span></h6>
                    </td>
                    <% end %>
                    <td class="align-middle">
                      <% if task.task_expire < Date.today %>
                        <h6 class="mb-0"><span class="badge bg-danger"><%= task.task_expire %></span></h6>
                        <span>Tarefa em atraso</span>
                      <% else %>
                        <h6 class="mb-0"><span class="badge bg-success"><%= task.task_expire %></span></h6>
                        <span>Tarefa no prazo</span>
                      <% end %>
                    </td>
                    <% if task.task_status? %>
                      <td class="align-middle">
                        <h6 class="mb-0"><span class="badge bg-success">Tarefa aberta</span></h6>
                      </td>
                      <td class="align-middle">
                            <%= button_to("View Post",task_path(id: task.id),method: :get, remote: true, :class => "btn btn-sm btn-success") %>
                            <%= button_to("Add Comment", new_task_comment_path(task_id: task.id),method: :get, remote: true, :class => "btn btn-sm btn-success") %>
                            <%= button_to('Concluido',update_status_task_path(id: task.id), method: :patch, remote: true, :class => "btn btn-sm btn-success") %>
                        </td>
                    <% else %>
                    <td class="align-middle">
                        <h6 class="mb-0"><span class="badge bg-danger">Tarefa fechada</span></h6>
                      </td>
                      <td class="align-middle">
                          <%= button_to("View Post",task_path(id: task.id),method: :get, remote: true, :class => "btn btn-sm btn-success") %>
                          <%= button_to('Reabrir',update_status_task_path(id: task.id), method: :patch, remote: true, :class => "btn btn-sm btn-success") %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
  </section>

app/views/tasks/new.html.erb

<%= button_to "logout", destroy_user_session_path, method: :delete  %>
<h1>Nova Task</h1>

<form action="/tasks" accept-charset="UTF-8" method="post">
    <%= form_with model: @task, multipart: true do |form| %>
        <div>
            <%= form.label :task_name %><br>
            <%= form.text_field :task_name %>
        </div>

        <div>
            <%= form.label :task_content %><br>
            <%= form.text_area :task_content %>
        </div>

        <div>
            <%= form.label :task_expire %><br>
            <%= form.date_field :task_expire, hide_label: true, class: 'datepicker' %>
        </div>

        <div>
            <%= form.label :task_urgency %><br>
            <%= form.select :task_urgency, [['Normal', '1'], ['Atenção', '2'], ['Urgente', '3']] %>
        </div>
        <div class="row">
            <div class="col-auto">
                <input name="role_ids" type="hidden" />
                <%= form.select :role_ids, @roles, { selected: @roles, object: @roles }, multiple: true %>
            </div>
        </div>

        <div>
            <%= form.submit %>
        </div>

    <% end %>
</form>

app/views/tasks/show.html.erb
<h1><%= @task.task_name %></h1>

<p><%= @task.task_content %></p>

<h2>Comments</h2>
<ul id="comments_list">
  <%= render @task.comments %>
</ul>
<% if @task.task_status? %>
  <%= link_to "Add Comment", new_task_comment_path(@task), remote: true %>
<% else %>
<% end %>

<div id="comment_form_container"></div>

<script>
  // JavaScript to handle the comment form popup
  document.addEventListener('DOMContentLoaded', function() {
    document.querySelector("a[data-remote='true']").addEventListener('click', function(event) {
      event.preventDefault();

      var url = this.getAttribute('href');
      var container = document.getElementById('comment_form_container');

      // Load the comment form into the container using AJAX
      var xhr = new XMLHttpRequest();
      xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          if (xhr.status === 200) {
            container.innerHTML = xhr.responseText;
          } else {
            console.error('Error loading comment form:', xhr.status);
          }
        }
      };
      xhr.open('GET', url, true);
      xhr.send();
    });
  });
</script>

app/views/tasks/update_status.js.erb
document.getElementById('status').innerHTML = 'Completed';